### ISSUE TITLE
Head and Tail Customizations are Improperly Set

### ISSUE THREAD

**Issue by bvanvugt** [BattlesnakeOfficial/starter-snake-java#8]
Head and Tail customizations are using the older API property names "headType" and "tailType". 

These should be updated for API v1 which uses "head" and "tail". 

Relevant code is here:
https://github.com/BattlesnakeOfficial/starter-snake-java/blob/master/src/main/java/com/battlesnake/starter/Snake.java#L106

**Comment by Nettogrof** [comment]
This issue can be close

**Comment by bvanvugt** [comment]
@Nettogrof cool thanks
